// In-memory mock database — mutated by mock-handler for stateful interactions.
// Resets on page refresh (acceptable for demo purposes).

import type { VerificationStatus, ApplicationStatus, NotificationType, PlatformName } from "@influencex/shared";

interface MockNotification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  read: boolean;
  link: string | null;
  createdAt: string;
}

export const MOCK_USERS = {
  "mock-user-brand-001": {
    id: "mock-user-brand-001",
    email: "brand@demo.com",
    role: "BRAND" as const,
    createdAt: "2025-01-15T10:00:00Z",
  },
  "mock-user-creator-001": {
    id: "mock-user-creator-001",
    email: "creator@demo.com",
    role: "INFLUENCER" as const,
    createdAt: "2025-01-20T10:00:00Z",
  },
  "mock-user-admin-001": {
    id: "mock-user-admin-001",
    email: "admin@influencex.com",
    role: "ADMIN" as const,
    createdAt: "2025-01-01T10:00:00Z",
  },
};

export const DEMO_CREDENTIALS: Record<string, { userId: string; password: string }> = {
  "brand@demo.com": { userId: "mock-user-brand-001", password: "demo123" },
  "creator@demo.com": { userId: "mock-user-creator-001", password: "demo123" },
  "admin@influencex.com": { userId: "mock-user-admin-001", password: "demo123" },
};

// ── Influencer directory (visible to all) ────────────────────────────────────

export const MOCK_DIRECTORY = [
  {
    id: "mock-influencer-001",
    displayName: "Priya Sharma",
    avatar: null,
    bio: "Fashion & lifestyle creator from Mumbai. I create authentic content that connects brands with real people.",
    niche: ["Fashion", "Lifestyle", "Beauty"],
    location: "Mumbai, India",
    followersCount: 170000,
    engagementRate: 3.8,
    minRate: 5000,
    rateCard: { perPost: 15000, perReel: 25000, perStory: 5000, perVideo: 35000 },
    verified: true,
    authenticityScore: 70,
    qualityFlags: ["SELF_REPORTED_ONLY"],
    platforms: [
      { id: "plat-001", name: "INSTAGRAM" as PlatformName, handle: "priya.sharma", followers: 125000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
      { id: "plat-002", name: "YOUTUBE" as PlatformName, handle: "PriyaSharmaVlogs", followers: 45000, verificationStatus: "UNVERIFIED" as VerificationStatus, verificationMethod: null as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
    ],
  },
  {
    id: "mock-influencer-002",
    displayName: "Rohit Mehta",
    avatar: null,
    bio: "Tech reviewer & gaming streamer. Honest reviews, zero sponsorship bias.",
    niche: ["Tech", "Gaming", "Reviews"],
    location: "Bengaluru, India",
    followersCount: 280000,
    engagementRate: 4.2,
    minRate: 12000,
    rateCard: { perPost: 18000, perReel: 30000, perVideo: 55000 },
    verified: true,
    authenticityScore: 88,
    qualityFlags: [],
    platforms: [
      { id: "plat-003", name: "YOUTUBE" as PlatformName, handle: "RohitTechReviews", followers: 210000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "AUTO_API" as string | null, apiFollowerCount: 214500 as number | null, apiEngagementRate: 4.1 as number | null },
      { id: "plat-004", name: "INSTAGRAM" as PlatformName, handle: "rohit.techie", followers: 70000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
    ],
  },
  {
    id: "mock-influencer-003",
    displayName: "Aisha Khan",
    avatar: null,
    bio: "Beauty & skincare expert. Cruelty-free, inclusive beauty for everyone.",
    niche: ["Beauty", "Skincare", "Wellness"],
    location: "Delhi, India",
    followersCount: 450000,
    engagementRate: 5.1,
    minRate: 30000,
    rateCard: { perPost: 35000, perReel: 55000, perStory: 10000 },
    verified: true,
    authenticityScore: 78,
    qualityFlags: ["SELF_REPORTED_ONLY"],
    platforms: [
      { id: "plat-005", name: "INSTAGRAM" as PlatformName, handle: "aisha.beauty", followers: 380000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
      { id: "plat-006", name: "YOUTUBE" as PlatformName, handle: "AishaKhanBeauty", followers: 70000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
    ],
  },
  {
    id: "mock-influencer-004",
    displayName: "Vikram Nair",
    avatar: null,
    bio: "Adventure travel blogger. Exploring hidden India one trip at a time.",
    niche: ["Travel", "Adventure", "Photography"],
    location: "Kochi, India",
    followersCount: 89000,
    engagementRate: 6.3,
    minRate: 8000,
    rateCard: { perPost: 10000, perReel: 18000, perStory: 4000 },
    verified: true,
    authenticityScore: 83,
    qualityFlags: [],
    platforms: [
      { id: "plat-007", name: "INSTAGRAM" as PlatformName, handle: "vikram.travels", followers: 72000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
      { id: "plat-008", name: "YOUTUBE" as PlatformName, handle: "VikramExplores", followers: 17000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "AUTO_API" as string | null, apiFollowerCount: 16800 as number | null, apiEngagementRate: 6.1 as number | null },
    ],
  },
  {
    id: "mock-influencer-005",
    displayName: "Sneha Gupta",
    avatar: null,
    bio: "Home chef & food blogger. Authentic Indian recipes with a modern twist.",
    niche: ["Food", "Cooking", "Lifestyle"],
    location: "Pune, India",
    followersCount: 200000,
    engagementRate: 4.7,
    minRate: 20000,
    rateCard: { perPost: 22000, perReel: 35000, perStory: 8000, perVideo: 45000 },
    verified: true,
    authenticityScore: 74,
    qualityFlags: ["SELF_REPORTED_ONLY"],
    platforms: [
      { id: "plat-009", name: "INSTAGRAM" as PlatformName, handle: "sneha.cooks", followers: 155000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
      { id: "plat-010", name: "YOUTUBE" as PlatformName, handle: "SnehaKitchen", followers: 45000, verificationStatus: "PENDING" as VerificationStatus, verificationMethod: null as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
    ],
  },
  {
    id: "mock-influencer-006",
    displayName: "Aryan Kapoor",
    avatar: null,
    bio: "Certified fitness trainer. Helping 500K+ people achieve their health goals.",
    niche: ["Fitness", "Health", "Nutrition"],
    location: "Mumbai, India",
    followersCount: 520000,
    engagementRate: 5.8,
    minRate: 25000,
    rateCard: { perPost: 30000, perReel: 50000, perStory: 12000, perVideo: 80000 },
    verified: true,
    authenticityScore: 91,
    qualityFlags: [],
    platforms: [
      { id: "plat-011", name: "INSTAGRAM" as PlatformName, handle: "aryan.fitness", followers: 420000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "MANUAL_ADMIN" as string | null, apiFollowerCount: null as number | null, apiEngagementRate: null as number | null },
      { id: "plat-012", name: "YOUTUBE" as PlatformName, handle: "AryanFit", followers: 100000, verificationStatus: "VERIFIED" as VerificationStatus, verificationMethod: "AUTO_API" as string | null, apiFollowerCount: 98200 as number | null, apiEngagementRate: 5.6 as number | null },
    ],
  },
];

// ── Mutable state ─────────────────────────────────────────────────────────────

export const db = {
  campaigns: [
    {
      id: "mock-camp-001",
      brandId: "mock-brand-001",
      brand: { name: "Zara Lifestyle", logo: null, verified: true },
      title: "Summer Fashion Collection 2025",
      description:
        "We're launching our summer collection and need micro + macro influencers in fashion and lifestyle to showcase our new arrivals in authentic, engaging content. Looking for creators who align with our brand values of style, sustainability, and inclusivity.",
      budget: 200000,
      budgetType: "FLAT_FEE",
      criteria: { minFollowers: 10000, platforms: ["INSTAGRAM", "YOUTUBE"], niches: ["Fashion", "Lifestyle", "Beauty"] },
      status: "ACTIVE",
      campaignCode: "ZARA-SUMMER-2025",
      startDate: "2025-07-01T00:00:00Z",
      endDate: "2025-08-31T00:00:00Z",
      createdAt: "2025-06-01T10:00:00Z",
      _count: { applications: 12 },
    },
    {
      id: "mock-camp-002",
      brandId: "mock-brand-001",
      brand: { name: "Zara Lifestyle", logo: null, verified: true },
      title: "Winter Wardrobe Festive Campaign",
      description:
        "Festive season campaign targeting fashion-forward audiences. We need creators to style our winter collection pieces and share their looks. Ideal for creators with strong fashion engagement.",
      budget: 350000,
      budgetType: "MIXED",
      criteria: { minFollowers: 50000, platforms: ["INSTAGRAM"], niches: ["Fashion"] },
      status: "ACTIVE",
      campaignCode: "ZARA-WINTER-2025",
      startDate: "2025-10-15T00:00:00Z",
      endDate: "2025-12-31T00:00:00Z",
      createdAt: "2025-06-10T10:00:00Z",
      _count: { applications: 7 },
    },
    {
      id: "mock-camp-003",
      brandId: "mock-brand-001",
      brand: { name: "Zara Lifestyle", logo: null, verified: true },
      title: "Brand Awareness Drive Q4",
      description:
        "Performance-based campaign for Q4 brand awareness. We track clicks and conversions with affiliate codes. Best for creators with highly engaged audiences.",
      budget: 120000,
      budgetType: "CPA",
      criteria: { minFollowers: 5000, platforms: ["INSTAGRAM", "YOUTUBE", "TWITTER"] },
      status: "DRAFT",
      campaignCode: "ZARA-Q4-AWARENESS",
      startDate: null,
      endDate: null,
      createdAt: "2025-06-15T10:00:00Z",
      _count: { applications: 0 },
    },
  ],

  hires: [
    {
      id: "mock-hire-001",
      brandId: "mock-brand-001",
      influencerId: "mock-influencer-001",
      title: "Instagram Reel for Summer Collection",
      description:
        "We'd love you to create an authentic Instagram Reel showcasing our Summer Collection 2025. The video should feel natural and reflect your personal style while featuring at least 3 pieces from our collection.",
      budget: 25000,
      deliverables: "1 Instagram Reel (60s min), 2 Stories with product tag, 1 feed post",
      deadline: "2025-08-15T00:00:00Z",
      status: "PENDING",
      brandMessage: "Hi Priya! We love your content and think you'd be a perfect fit for our summer campaign. Looking forward to working together!",
      createdAt: "2025-06-18T10:00:00Z",
      brand: { id: "mock-brand-001", name: "Zara Lifestyle", logo: null, verified: true, industry: "Fashion & Apparel" },
      influencer: { id: "mock-influencer-001", displayName: "Priya Sharma", avatar: null, verified: false, niche: ["Fashion", "Lifestyle", "Beauty"] },
    },
    {
      id: "mock-hire-002",
      brandId: "mock-brand-001",
      influencerId: "mock-influencer-002",
      title: "YouTube Review — Summer Style Guide",
      description:
        "Create a YouTube video reviewing and styling our summer collection pieces. Include an honest review and outfit ideas for different occasions.",
      budget: 45000,
      deliverables: "1 YouTube video (8–10 min), 3 Instagram Stories, 1 YouTube Community post",
      deadline: "2025-09-01T00:00:00Z",
      status: "ACCEPTED",
      brandMessage: "Hey Rohit! Big fan of your style review content. Would love you to cover our summer line.",
      createdAt: "2025-06-12T10:00:00Z",
      brand: { id: "mock-brand-001", name: "Zara Lifestyle", logo: null, verified: true, industry: "Fashion & Apparel" },
      influencer: { id: "mock-influencer-002", displayName: "Rohit Mehta", avatar: null, verified: true, niche: ["Tech", "Gaming", "Reviews"] },
    },
  ],

  applications: [
    {
      id: "mock-app-001",
      campaignId: "mock-camp-001",
      influencerId: "mock-influencer-001",
      status: "PENDING" as ApplicationStatus,
      pitch: "I would love to collaborate on the Summer Collection campaign! Fashion is my niche and I have a highly engaged audience in Mumbai. My Instagram reels average 15K+ views.",
      createdAt: "2025-06-20T10:00:00Z",
      campaign: {
        id: "mock-camp-001",
        title: "Summer Fashion Collection 2025",
        brand: { name: "Zara Lifestyle", logo: null, verified: true },
        budget: 200000,
        budgetType: "FLAT_FEE",
      },
      influencer: {
        id: "mock-influencer-001",
        displayName: "Priya Sharma",
        avatar: null as string | null,
        followersCount: 170000,
        niche: ["Fashion", "Lifestyle", "Beauty"],
        platforms: [
          { id: "plat-001", name: "INSTAGRAM" as const, handle: "priya.sharma", followers: 125000 },
          { id: "plat-002", name: "YOUTUBE" as const, handle: "PriyaSharmaVlogs", followers: 45000 },
        ],
        verified: false,
      },
    },
    {
      id: "mock-app-002",
      campaignId: "mock-camp-001",
      influencerId: "mock-influencer-002",
      status: "SHORTLISTED" as ApplicationStatus,
      pitch: "My audience is highly engaged with fashion and lifestyle content. I've partnered with multiple apparel brands and can deliver authentic storytelling that drives real conversions.",
      createdAt: "2025-06-19T08:00:00Z",
      campaign: {
        id: "mock-camp-001",
        title: "Summer Fashion Collection 2025",
        brand: { name: "Zara Lifestyle", logo: null, verified: true },
        budget: 200000,
        budgetType: "FLAT_FEE",
      },
      influencer: {
        id: "mock-influencer-002",
        displayName: "Rohit Mehta",
        avatar: null as string | null,
        followersCount: 280000,
        niche: ["Tech", "Gaming", "Reviews"],
        platforms: [
          { id: "plat-003", name: "YOUTUBE" as const, handle: "RohitTechReviews", followers: 210000 },
          { id: "plat-004", name: "INSTAGRAM" as const, handle: "rohit.techie", followers: 70000 },
        ],
        verified: true,
      },
    },
    {
      id: "mock-app-003",
      campaignId: "mock-camp-001",
      influencerId: "mock-influencer-003",
      status: "APPROVED" as ApplicationStatus,
      pitch: "Fashion and beauty content is what I do best. 450K+ followers across platforms, 5%+ engagement rate, and a track record of successful brand campaigns. Let's create something stunning together!",
      createdAt: "2025-06-18T14:30:00Z",
      campaign: {
        id: "mock-camp-001",
        title: "Summer Fashion Collection 2025",
        brand: { name: "Zara Lifestyle", logo: null, verified: true },
        budget: 200000,
        budgetType: "FLAT_FEE",
      },
      influencer: {
        id: "mock-influencer-003",
        displayName: "Aisha Khan",
        avatar: null as string | null,
        followersCount: 450000,
        niche: ["Beauty", "Skincare", "Wellness"],
        platforms: [
          { id: "plat-005", name: "INSTAGRAM" as const, handle: "aisha.beauty", followers: 380000 },
          { id: "plat-006", name: "YOUTUBE" as const, handle: "AishaKhanBeauty", followers: 70000 },
        ],
        verified: true,
      },
    },
    {
      id: "mock-app-004",
      campaignId: "mock-camp-002",
      influencerId: "mock-influencer-004",
      status: "PENDING" as ApplicationStatus,
      pitch: "Winter fashion is my favourite. I travel across India and document authentic styling in diverse locations. My audience trusts my fashion picks.",
      createdAt: "2025-06-17T09:00:00Z",
      campaign: {
        id: "mock-camp-002",
        title: "Winter Wardrobe Festive Campaign",
        brand: { name: "Zara Lifestyle", logo: null, verified: true },
        budget: 350000,
        budgetType: "MIXED",
      },
      influencer: {
        id: "mock-influencer-004",
        displayName: "Vikram Nair",
        avatar: null as string | null,
        followersCount: 89000,
        niche: ["Travel", "Adventure", "Photography"],
        platforms: [
          { id: "plat-007", name: "INSTAGRAM" as const, handle: "vikram.travels", followers: 72000 },
        ],
        verified: true,
      },
    },
  ],

  notifications: {
    "mock-user-brand-001": [
      {
        id: "notif-b-001",
        type: "APPLICATION_RECEIVED" as NotificationType,
        title: "New application — Summer Fashion Collection 2025",
        body: "Priya Sharma (170K followers) applied to your campaign with a pitch.",
        read: false,
        link: "/dashboard/campaigns/mock-camp-001",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-b-002",
        type: "APPLICATION_RECEIVED" as NotificationType,
        title: "New application — Summer Fashion Collection 2025",
        body: "Aisha Khan (450K followers) applied with a compelling pitch.",
        read: false,
        link: "/dashboard/campaigns/mock-camp-001",
        createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-b-003",
        type: "HIRE_ACCEPTED" as NotificationType,
        title: "Hire request accepted — Rohit Mehta",
        body: 'Rohit Mehta accepted your hire request for "YouTube Review — Summer Style Guide".',
        read: true,
        link: "/dashboard/hires",
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-b-004",
        type: "APPLICATION_RECEIVED" as NotificationType,
        title: "New application — Winter Wardrobe Festive Campaign",
        body: "Vikram Nair (89K followers) applied to your festive campaign.",
        read: true,
        link: "/dashboard/campaigns/mock-camp-002",
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ] as MockNotification[],

    "mock-user-creator-001": [
      {
        id: "notif-c-001",
        type: "APPLICATION_SHORTLISTED" as NotificationType,
        title: "You've been shortlisted!",
        body: 'Zara Lifestyle shortlisted your application for "Summer Fashion Collection 2025".',
        read: false,
        link: "/dashboard/applications",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-c-002",
        type: "HIRE_REQUEST" as NotificationType,
        title: "New direct hire request from Zara Lifestyle",
        body: "You've been invited to create an Instagram Reel for the Summer Collection. Budget: ₹25,000.",
        read: false,
        link: "/dashboard/hires",
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-c-003",
        type: "APPLICATION_APPROVED" as NotificationType,
        title: "Application approved 🎉",
        body: 'Your application for "Summer Fashion Collection 2025" has been approved by Zara Lifestyle.',
        read: true,
        link: "/dashboard/applications",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "notif-c-004",
        type: "VERIFICATION_FAILED" as NotificationType,
        title: "Verification not completed",
        body: "Your Instagram handle could not be verified — the code was not found in your bio. Please try again.",
        read: true,
        link: "/dashboard/profile",
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ] as MockNotification[],

    "mock-user-admin-001": [] as MockNotification[],
  },

  // The logged-in creator's own editable profile
  influencerProfile: {
    id: "mock-influencer-001",
    userId: "mock-user-creator-001",
    displayName: "Priya Sharma",
    avatar: null as string | null,
    bio: "Fashion & lifestyle creator from Mumbai. I create authentic content that connects brands with real people.",
    niche: ["Fashion", "Lifestyle", "Beauty"],
    location: "Mumbai, India",
    followersCount: 170000,
    engagementRate: 3.8,
    rateCard: { perPost: 15000, perReel: 25000, perStory: 5000, perVideo: 35000 } as Record<string, number> | null,
    minRate: 5000 as number | null,
    profileCompleted: true,
    verified: false,
    authenticityScore: 50 as number,
    qualityFlags: ["SELF_REPORTED_ONLY"] as string[],
    platforms: [
      {
        id: "plat-001",
        name: "INSTAGRAM" as PlatformName,
        handle: "priya.sharma",
        followers: 125000,
        verified: false,
        verificationCode: "IFX-A3KM9X",
        verificationStatus: "UNVERIFIED" as VerificationStatus,
        verificationMethod: null as string | null,
        verifiedAt: null as string | null,
        apiFollowerCount: null as number | null,
        apiEngagementRate: null as number | null,
        createdAt: "2025-01-20T12:00:00Z",
      },
      {
        id: "plat-002",
        name: "YOUTUBE" as PlatformName,
        handle: "PriyaSharmaVlogs",
        followers: 45000,
        verified: false,
        verificationCode: "IFX-B7YP2Q",
        verificationStatus: "PENDING" as VerificationStatus,
        verificationMethod: null as string | null,
        verifiedAt: null as string | null,
        apiFollowerCount: null as number | null,
        apiEngagementRate: null as number | null,
        createdAt: "2025-01-20T12:05:00Z",
      },
    ],
    _count: { applications: 2, directHires: 1 },
    createdAt: "2025-01-20T10:00:00Z",
  },
};
